// DO NOT EDIT. Generated by scripts/edid-timings/build-edid-timings.swift from
// data/edid-timings/vesa-dmt.csv and data/edid-timings/cta-861-vic.csv.
//
// Sources of record:
//   VESA DMT Standard v1.0 Rev 13 (https://glenwing.github.io/docs/VESA-DMT-1.13.pdf)
//   ANSI/CTA-861-H (https://archive.org/download/ansi-cta-861-h-final/ANSI-CTA-861-H-Final.pdf)
//
// Both CSVs are cross-checked against edid-decode (MIT, commit
// f341ed8e3742118a86619e5f499017db2de30d94) and the Linux kernel's
// drm_edid.c (GPL-2.0, numeric cross-check only) by
// scripts/edid-timings/check-edid-timings.py before this file is generated.
//
// Regenerate: swift scripts/edid-timings/build-edid-timings.swift
// Check only: swift scripts/edid-timings/build-edid-timings.swift --check

public enum EDIDTimingTables {
    public struct DMTTiming: Hashable, Sendable {
        public let id: Int            // DMT ID, 0x01...0x58
        public let width: Int
        public let height: Int
        public let hTotal: Int
        public let vTotal: Int
        public let pixelClockKHz: Int
        public let interlaced: Bool
        public let reducedBlanking: Bool
        public let standardCode: UInt16?   // EDID 2-byte standard timing code, big-endian as printed in the spec
        public let cvtCode: UInt32?        // 3-byte CVT code, 0xRRGGBB as printed

        public init(
            id: Int,
            width: Int,
            height: Int,
            hTotal: Int,
            vTotal: Int,
            pixelClockKHz: Int,
            interlaced: Bool,
            reducedBlanking: Bool,
            standardCode: UInt16?,
            cvtCode: UInt32?
        ) {
            self.id = id
            self.width = width
            self.height = height
            self.hTotal = hTotal
            self.vTotal = vTotal
            self.pixelClockKHz = pixelClockKHz
            self.interlaced = interlaced
            self.reducedBlanking = reducedBlanking
            self.standardCode = standardCode
            self.cvtCode = cvtCode
        }
    }

    public struct VICTiming: Hashable, Sendable {
        public let vic: Int
        public let width: Int
        public let height: Int
        public let hTotal: Int
        public let vTotal: Int             // frame total for interlaced (e.g. 1125 for VIC 5)
        public let pixelClockKHz: Int
        public let interlaced: Bool

        public init(
            vic: Int,
            width: Int,
            height: Int,
            hTotal: Int,
            vTotal: Int,
            pixelClockKHz: Int,
            interlaced: Bool
        ) {
            self.vic = vic
            self.width = width
            self.height = height
            self.hTotal = hTotal
            self.vTotal = vTotal
            self.pixelClockKHz = pixelClockKHz
            self.interlaced = interlaced
        }
    }

    public static let dmt: [Int: DMTTiming] = [
        0x01: DMTTiming(id: 0x01, width: 640, height: 350, hTotal: 832, vTotal: 445, pixelClockKHz: 31500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x02: DMTTiming(id: 0x02, width: 640, height: 400, hTotal: 832, vTotal: 445, pixelClockKHz: 31500, interlaced: false, reducedBlanking: false, standardCode: 0x3119, cvtCode: nil),
        0x03: DMTTiming(id: 0x03, width: 720, height: 400, hTotal: 936, vTotal: 446, pixelClockKHz: 35500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x04: DMTTiming(id: 0x04, width: 640, height: 480, hTotal: 800, vTotal: 525, pixelClockKHz: 25175, interlaced: false, reducedBlanking: false, standardCode: 0x3140, cvtCode: nil),
        0x05: DMTTiming(id: 0x05, width: 640, height: 480, hTotal: 832, vTotal: 520, pixelClockKHz: 31500, interlaced: false, reducedBlanking: false, standardCode: 0x314C, cvtCode: nil),
        0x06: DMTTiming(id: 0x06, width: 640, height: 480, hTotal: 840, vTotal: 500, pixelClockKHz: 31500, interlaced: false, reducedBlanking: false, standardCode: 0x314F, cvtCode: nil),
        0x07: DMTTiming(id: 0x07, width: 640, height: 480, hTotal: 832, vTotal: 509, pixelClockKHz: 36000, interlaced: false, reducedBlanking: false, standardCode: 0x3159, cvtCode: nil),
        0x08: DMTTiming(id: 0x08, width: 800, height: 600, hTotal: 1024, vTotal: 625, pixelClockKHz: 36000, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x09: DMTTiming(id: 0x09, width: 800, height: 600, hTotal: 1056, vTotal: 628, pixelClockKHz: 40000, interlaced: false, reducedBlanking: false, standardCode: 0x4540, cvtCode: nil),
        0x0A: DMTTiming(id: 0x0A, width: 800, height: 600, hTotal: 1040, vTotal: 666, pixelClockKHz: 50000, interlaced: false, reducedBlanking: false, standardCode: 0x454C, cvtCode: nil),
        0x0B: DMTTiming(id: 0x0B, width: 800, height: 600, hTotal: 1056, vTotal: 625, pixelClockKHz: 49500, interlaced: false, reducedBlanking: false, standardCode: 0x454F, cvtCode: nil),
        0x0C: DMTTiming(id: 0x0C, width: 800, height: 600, hTotal: 1048, vTotal: 631, pixelClockKHz: 56250, interlaced: false, reducedBlanking: false, standardCode: 0x4559, cvtCode: nil),
        0x0D: DMTTiming(id: 0x0D, width: 800, height: 600, hTotal: 960, vTotal: 636, pixelClockKHz: 73250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x0E: DMTTiming(id: 0x0E, width: 848, height: 480, hTotal: 1088, vTotal: 517, pixelClockKHz: 33750, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x0F: DMTTiming(id: 0x0F, width: 1024, height: 768, hTotal: 1264, vTotal: 817, pixelClockKHz: 44900, interlaced: true, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x10: DMTTiming(id: 0x10, width: 1024, height: 768, hTotal: 1344, vTotal: 806, pixelClockKHz: 65000, interlaced: false, reducedBlanking: false, standardCode: 0x6140, cvtCode: nil),
        0x11: DMTTiming(id: 0x11, width: 1024, height: 768, hTotal: 1328, vTotal: 806, pixelClockKHz: 75000, interlaced: false, reducedBlanking: false, standardCode: 0x614A, cvtCode: nil),
        0x12: DMTTiming(id: 0x12, width: 1024, height: 768, hTotal: 1312, vTotal: 800, pixelClockKHz: 78750, interlaced: false, reducedBlanking: false, standardCode: 0x614F, cvtCode: nil),
        0x13: DMTTiming(id: 0x13, width: 1024, height: 768, hTotal: 1376, vTotal: 808, pixelClockKHz: 94500, interlaced: false, reducedBlanking: false, standardCode: 0x6159, cvtCode: nil),
        0x14: DMTTiming(id: 0x14, width: 1024, height: 768, hTotal: 1184, vTotal: 813, pixelClockKHz: 115500, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x15: DMTTiming(id: 0x15, width: 1152, height: 864, hTotal: 1600, vTotal: 900, pixelClockKHz: 108000, interlaced: false, reducedBlanking: false, standardCode: 0x714F, cvtCode: nil),
        0x16: DMTTiming(id: 0x16, width: 1280, height: 768, hTotal: 1440, vTotal: 790, pixelClockKHz: 68250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0x7F1C21),
        0x17: DMTTiming(id: 0x17, width: 1280, height: 768, hTotal: 1664, vTotal: 798, pixelClockKHz: 79500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: 0x7F1C28),
        0x18: DMTTiming(id: 0x18, width: 1280, height: 768, hTotal: 1696, vTotal: 805, pixelClockKHz: 102250, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: 0x7F1C44),
        0x19: DMTTiming(id: 0x19, width: 1280, height: 768, hTotal: 1712, vTotal: 809, pixelClockKHz: 117500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: 0x7F1C62),
        0x1A: DMTTiming(id: 0x1A, width: 1280, height: 768, hTotal: 1440, vTotal: 813, pixelClockKHz: 140250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x1B: DMTTiming(id: 0x1B, width: 1280, height: 800, hTotal: 1440, vTotal: 823, pixelClockKHz: 71000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0x8F1821),
        0x1C: DMTTiming(id: 0x1C, width: 1280, height: 800, hTotal: 1680, vTotal: 831, pixelClockKHz: 83500, interlaced: false, reducedBlanking: false, standardCode: 0x8100, cvtCode: 0x8F1828),
        0x1D: DMTTiming(id: 0x1D, width: 1280, height: 800, hTotal: 1696, vTotal: 838, pixelClockKHz: 106500, interlaced: false, reducedBlanking: false, standardCode: 0x810F, cvtCode: 0x8F1844),
        0x1E: DMTTiming(id: 0x1E, width: 1280, height: 800, hTotal: 1712, vTotal: 843, pixelClockKHz: 122500, interlaced: false, reducedBlanking: false, standardCode: 0x8119, cvtCode: 0x8F1862),
        0x1F: DMTTiming(id: 0x1F, width: 1280, height: 800, hTotal: 1440, vTotal: 847, pixelClockKHz: 146250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x20: DMTTiming(id: 0x20, width: 1280, height: 960, hTotal: 1800, vTotal: 1000, pixelClockKHz: 108000, interlaced: false, reducedBlanking: false, standardCode: 0x8140, cvtCode: nil),
        0x21: DMTTiming(id: 0x21, width: 1280, height: 960, hTotal: 1728, vTotal: 1011, pixelClockKHz: 148500, interlaced: false, reducedBlanking: false, standardCode: 0x8159, cvtCode: nil),
        0x22: DMTTiming(id: 0x22, width: 1280, height: 960, hTotal: 1440, vTotal: 1017, pixelClockKHz: 175500, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x23: DMTTiming(id: 0x23, width: 1280, height: 1024, hTotal: 1688, vTotal: 1066, pixelClockKHz: 108000, interlaced: false, reducedBlanking: false, standardCode: 0x8180, cvtCode: nil),
        0x24: DMTTiming(id: 0x24, width: 1280, height: 1024, hTotal: 1688, vTotal: 1066, pixelClockKHz: 135000, interlaced: false, reducedBlanking: false, standardCode: 0x818F, cvtCode: nil),
        0x25: DMTTiming(id: 0x25, width: 1280, height: 1024, hTotal: 1728, vTotal: 1072, pixelClockKHz: 157500, interlaced: false, reducedBlanking: false, standardCode: 0x8199, cvtCode: nil),
        0x26: DMTTiming(id: 0x26, width: 1280, height: 1024, hTotal: 1440, vTotal: 1084, pixelClockKHz: 187250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x27: DMTTiming(id: 0x27, width: 1360, height: 768, hTotal: 1792, vTotal: 795, pixelClockKHz: 85500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x28: DMTTiming(id: 0x28, width: 1360, height: 768, hTotal: 1520, vTotal: 813, pixelClockKHz: 148250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x29: DMTTiming(id: 0x29, width: 1400, height: 1050, hTotal: 1560, vTotal: 1080, pixelClockKHz: 101000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0x0C2021),
        0x2A: DMTTiming(id: 0x2A, width: 1400, height: 1050, hTotal: 1864, vTotal: 1089, pixelClockKHz: 121750, interlaced: false, reducedBlanking: false, standardCode: 0x9040, cvtCode: 0x0C2028),
        0x2B: DMTTiming(id: 0x2B, width: 1400, height: 1050, hTotal: 1896, vTotal: 1099, pixelClockKHz: 156000, interlaced: false, reducedBlanking: false, standardCode: 0x904F, cvtCode: 0x0C2044),
        0x2C: DMTTiming(id: 0x2C, width: 1400, height: 1050, hTotal: 1912, vTotal: 1105, pixelClockKHz: 179500, interlaced: false, reducedBlanking: false, standardCode: 0x9059, cvtCode: 0x0C2062),
        0x2D: DMTTiming(id: 0x2D, width: 1400, height: 1050, hTotal: 1560, vTotal: 1112, pixelClockKHz: 208000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x2E: DMTTiming(id: 0x2E, width: 1440, height: 900, hTotal: 1600, vTotal: 926, pixelClockKHz: 88750, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0xC11821),
        0x2F: DMTTiming(id: 0x2F, width: 1440, height: 900, hTotal: 1904, vTotal: 934, pixelClockKHz: 106500, interlaced: false, reducedBlanking: false, standardCode: 0x9500, cvtCode: 0xC11828),
        0x30: DMTTiming(id: 0x30, width: 1440, height: 900, hTotal: 1936, vTotal: 942, pixelClockKHz: 136750, interlaced: false, reducedBlanking: false, standardCode: 0x950F, cvtCode: 0xC11844),
        0x31: DMTTiming(id: 0x31, width: 1440, height: 900, hTotal: 1952, vTotal: 948, pixelClockKHz: 157000, interlaced: false, reducedBlanking: false, standardCode: 0x9519, cvtCode: 0xC11868),
        0x32: DMTTiming(id: 0x32, width: 1440, height: 900, hTotal: 1600, vTotal: 953, pixelClockKHz: 182750, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x33: DMTTiming(id: 0x33, width: 1600, height: 1200, hTotal: 2160, vTotal: 1250, pixelClockKHz: 162000, interlaced: false, reducedBlanking: false, standardCode: 0xA940, cvtCode: nil),
        0x34: DMTTiming(id: 0x34, width: 1600, height: 1200, hTotal: 2160, vTotal: 1250, pixelClockKHz: 175500, interlaced: false, reducedBlanking: false, standardCode: 0xA945, cvtCode: nil),
        0x35: DMTTiming(id: 0x35, width: 1600, height: 1200, hTotal: 2160, vTotal: 1250, pixelClockKHz: 189000, interlaced: false, reducedBlanking: false, standardCode: 0xA94A, cvtCode: nil),
        0x36: DMTTiming(id: 0x36, width: 1600, height: 1200, hTotal: 2160, vTotal: 1250, pixelClockKHz: 202500, interlaced: false, reducedBlanking: false, standardCode: 0xA94F, cvtCode: nil),
        0x37: DMTTiming(id: 0x37, width: 1600, height: 1200, hTotal: 2160, vTotal: 1250, pixelClockKHz: 229500, interlaced: false, reducedBlanking: false, standardCode: 0xA959, cvtCode: nil),
        0x38: DMTTiming(id: 0x38, width: 1600, height: 1200, hTotal: 1760, vTotal: 1271, pixelClockKHz: 268250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x39: DMTTiming(id: 0x39, width: 1680, height: 1050, hTotal: 1840, vTotal: 1080, pixelClockKHz: 119000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0x0C2821),
        0x3A: DMTTiming(id: 0x3A, width: 1680, height: 1050, hTotal: 2240, vTotal: 1089, pixelClockKHz: 146250, interlaced: false, reducedBlanking: false, standardCode: 0xB300, cvtCode: 0x0C2828),
        0x3B: DMTTiming(id: 0x3B, width: 1680, height: 1050, hTotal: 2272, vTotal: 1099, pixelClockKHz: 187000, interlaced: false, reducedBlanking: false, standardCode: 0xB30F, cvtCode: 0x0C2844),
        0x3C: DMTTiming(id: 0x3C, width: 1680, height: 1050, hTotal: 2288, vTotal: 1105, pixelClockKHz: 214750, interlaced: false, reducedBlanking: false, standardCode: 0xB319, cvtCode: 0x0C2868),
        0x3D: DMTTiming(id: 0x3D, width: 1680, height: 1050, hTotal: 1840, vTotal: 1112, pixelClockKHz: 245500, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x3E: DMTTiming(id: 0x3E, width: 1792, height: 1344, hTotal: 2448, vTotal: 1394, pixelClockKHz: 204750, interlaced: false, reducedBlanking: false, standardCode: 0xC140, cvtCode: nil),
        0x3F: DMTTiming(id: 0x3F, width: 1792, height: 1344, hTotal: 2456, vTotal: 1417, pixelClockKHz: 261000, interlaced: false, reducedBlanking: false, standardCode: 0xC14F, cvtCode: nil),
        0x40: DMTTiming(id: 0x40, width: 1792, height: 1344, hTotal: 1952, vTotal: 1423, pixelClockKHz: 333250, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x41: DMTTiming(id: 0x41, width: 1856, height: 1392, hTotal: 2528, vTotal: 1439, pixelClockKHz: 218250, interlaced: false, reducedBlanking: false, standardCode: 0xC940, cvtCode: nil),
        0x42: DMTTiming(id: 0x42, width: 1856, height: 1392, hTotal: 2560, vTotal: 1500, pixelClockKHz: 288000, interlaced: false, reducedBlanking: false, standardCode: 0xC94F, cvtCode: nil),
        0x43: DMTTiming(id: 0x43, width: 1856, height: 1392, hTotal: 2016, vTotal: 1474, pixelClockKHz: 356500, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x44: DMTTiming(id: 0x44, width: 1920, height: 1200, hTotal: 2080, vTotal: 1235, pixelClockKHz: 154000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0x572821),
        0x45: DMTTiming(id: 0x45, width: 1920, height: 1200, hTotal: 2592, vTotal: 1245, pixelClockKHz: 193250, interlaced: false, reducedBlanking: false, standardCode: 0xD100, cvtCode: 0x572828),
        0x46: DMTTiming(id: 0x46, width: 1920, height: 1200, hTotal: 2608, vTotal: 1255, pixelClockKHz: 245250, interlaced: false, reducedBlanking: false, standardCode: 0xD10F, cvtCode: 0x572844),
        0x47: DMTTiming(id: 0x47, width: 1920, height: 1200, hTotal: 2624, vTotal: 1262, pixelClockKHz: 281250, interlaced: false, reducedBlanking: false, standardCode: 0xD119, cvtCode: 0x572862),
        0x48: DMTTiming(id: 0x48, width: 1920, height: 1200, hTotal: 2080, vTotal: 1271, pixelClockKHz: 317000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x49: DMTTiming(id: 0x49, width: 1920, height: 1440, hTotal: 2600, vTotal: 1500, pixelClockKHz: 234000, interlaced: false, reducedBlanking: false, standardCode: 0xD140, cvtCode: nil),
        0x4A: DMTTiming(id: 0x4A, width: 1920, height: 1440, hTotal: 2640, vTotal: 1500, pixelClockKHz: 297000, interlaced: false, reducedBlanking: false, standardCode: 0xD14F, cvtCode: nil),
        0x4B: DMTTiming(id: 0x4B, width: 1920, height: 1440, hTotal: 2080, vTotal: 1525, pixelClockKHz: 380500, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x4C: DMTTiming(id: 0x4C, width: 2560, height: 1600, hTotal: 2720, vTotal: 1646, pixelClockKHz: 268500, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: 0x1F3821),
        0x4D: DMTTiming(id: 0x4D, width: 2560, height: 1600, hTotal: 3504, vTotal: 1658, pixelClockKHz: 348500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: 0x1F3828),
        0x4E: DMTTiming(id: 0x4E, width: 2560, height: 1600, hTotal: 3536, vTotal: 1672, pixelClockKHz: 443250, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: 0x1F3844),
        0x4F: DMTTiming(id: 0x4F, width: 2560, height: 1600, hTotal: 3536, vTotal: 1682, pixelClockKHz: 505250, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: 0x1F3862),
        0x50: DMTTiming(id: 0x50, width: 2560, height: 1600, hTotal: 2720, vTotal: 1694, pixelClockKHz: 552750, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x51: DMTTiming(id: 0x51, width: 1366, height: 768, hTotal: 1792, vTotal: 798, pixelClockKHz: 85500, interlaced: false, reducedBlanking: false, standardCode: nil, cvtCode: nil),
        0x52: DMTTiming(id: 0x52, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 148500, interlaced: false, reducedBlanking: false, standardCode: 0xD1C0, cvtCode: nil),
        0x53: DMTTiming(id: 0x53, width: 1600, height: 900, hTotal: 1800, vTotal: 1000, pixelClockKHz: 108000, interlaced: false, reducedBlanking: true, standardCode: 0xA9C0, cvtCode: nil),
        0x54: DMTTiming(id: 0x54, width: 2048, height: 1152, hTotal: 2250, vTotal: 1200, pixelClockKHz: 162000, interlaced: false, reducedBlanking: true, standardCode: 0xE1C0, cvtCode: nil),
        0x55: DMTTiming(id: 0x55, width: 1280, height: 720, hTotal: 1650, vTotal: 750, pixelClockKHz: 74250, interlaced: false, reducedBlanking: false, standardCode: 0x81C0, cvtCode: nil),
        0x56: DMTTiming(id: 0x56, width: 1366, height: 768, hTotal: 1500, vTotal: 800, pixelClockKHz: 72000, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x57: DMTTiming(id: 0x57, width: 4096, height: 2160, hTotal: 4176, vTotal: 2222, pixelClockKHz: 556744, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
        0x58: DMTTiming(id: 0x58, width: 4096, height: 2160, hTotal: 4176, vTotal: 2222, pixelClockKHz: 556188, interlaced: false, reducedBlanking: true, standardCode: nil, cvtCode: nil),
    ]

    public static let vic: [Int: VICTiming] = [
        1: VICTiming(vic: 1, width: 640, height: 480, hTotal: 800, vTotal: 525, pixelClockKHz: 25175, interlaced: false),
        2: VICTiming(vic: 2, width: 720, height: 480, hTotal: 858, vTotal: 525, pixelClockKHz: 27000, interlaced: false),
        3: VICTiming(vic: 3, width: 720, height: 480, hTotal: 858, vTotal: 525, pixelClockKHz: 27000, interlaced: false),
        4: VICTiming(vic: 4, width: 1280, height: 720, hTotal: 1650, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        5: VICTiming(vic: 5, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 74250, interlaced: true),
        6: VICTiming(vic: 6, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 27000, interlaced: true),
        7: VICTiming(vic: 7, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 27000, interlaced: true),
        8: VICTiming(vic: 8, width: 1440, height: 240, hTotal: 1716, vTotal: 262, pixelClockKHz: 27000, interlaced: false),
        9: VICTiming(vic: 9, width: 1440, height: 240, hTotal: 1716, vTotal: 262, pixelClockKHz: 27000, interlaced: false),
        10: VICTiming(vic: 10, width: 2880, height: 480, hTotal: 3432, vTotal: 525, pixelClockKHz: 54000, interlaced: true),
        11: VICTiming(vic: 11, width: 2880, height: 480, hTotal: 3432, vTotal: 525, pixelClockKHz: 54000, interlaced: true),
        12: VICTiming(vic: 12, width: 2880, height: 240, hTotal: 3432, vTotal: 262, pixelClockKHz: 54000, interlaced: false),
        13: VICTiming(vic: 13, width: 2880, height: 240, hTotal: 3432, vTotal: 262, pixelClockKHz: 54000, interlaced: false),
        14: VICTiming(vic: 14, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 54000, interlaced: false),
        15: VICTiming(vic: 15, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 54000, interlaced: false),
        16: VICTiming(vic: 16, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 148500, interlaced: false),
        17: VICTiming(vic: 17, width: 720, height: 576, hTotal: 864, vTotal: 625, pixelClockKHz: 27000, interlaced: false),
        18: VICTiming(vic: 18, width: 720, height: 576, hTotal: 864, vTotal: 625, pixelClockKHz: 27000, interlaced: false),
        19: VICTiming(vic: 19, width: 1280, height: 720, hTotal: 1980, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        20: VICTiming(vic: 20, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 74250, interlaced: true),
        21: VICTiming(vic: 21, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 27000, interlaced: true),
        22: VICTiming(vic: 22, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 27000, interlaced: true),
        23: VICTiming(vic: 23, width: 1440, height: 288, hTotal: 1728, vTotal: 312, pixelClockKHz: 27000, interlaced: false),
        24: VICTiming(vic: 24, width: 1440, height: 288, hTotal: 1728, vTotal: 312, pixelClockKHz: 27000, interlaced: false),
        25: VICTiming(vic: 25, width: 2880, height: 576, hTotal: 3456, vTotal: 625, pixelClockKHz: 54000, interlaced: true),
        26: VICTiming(vic: 26, width: 2880, height: 576, hTotal: 3456, vTotal: 625, pixelClockKHz: 54000, interlaced: true),
        27: VICTiming(vic: 27, width: 2880, height: 288, hTotal: 3456, vTotal: 312, pixelClockKHz: 54000, interlaced: false),
        28: VICTiming(vic: 28, width: 2880, height: 288, hTotal: 3456, vTotal: 312, pixelClockKHz: 54000, interlaced: false),
        29: VICTiming(vic: 29, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 54000, interlaced: false),
        30: VICTiming(vic: 30, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 54000, interlaced: false),
        31: VICTiming(vic: 31, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 148500, interlaced: false),
        32: VICTiming(vic: 32, width: 1920, height: 1080, hTotal: 2750, vTotal: 1125, pixelClockKHz: 74250, interlaced: false),
        33: VICTiming(vic: 33, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 74250, interlaced: false),
        34: VICTiming(vic: 34, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 74250, interlaced: false),
        35: VICTiming(vic: 35, width: 2880, height: 480, hTotal: 3432, vTotal: 525, pixelClockKHz: 108000, interlaced: false),
        36: VICTiming(vic: 36, width: 2880, height: 480, hTotal: 3432, vTotal: 525, pixelClockKHz: 108000, interlaced: false),
        37: VICTiming(vic: 37, width: 2880, height: 576, hTotal: 3456, vTotal: 625, pixelClockKHz: 108000, interlaced: false),
        38: VICTiming(vic: 38, width: 2880, height: 576, hTotal: 3456, vTotal: 625, pixelClockKHz: 108000, interlaced: false),
        39: VICTiming(vic: 39, width: 1920, height: 1080, hTotal: 2304, vTotal: 1250, pixelClockKHz: 72000, interlaced: true),
        40: VICTiming(vic: 40, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 148500, interlaced: true),
        41: VICTiming(vic: 41, width: 1280, height: 720, hTotal: 1980, vTotal: 750, pixelClockKHz: 148500, interlaced: false),
        42: VICTiming(vic: 42, width: 720, height: 576, hTotal: 864, vTotal: 625, pixelClockKHz: 54000, interlaced: false),
        43: VICTiming(vic: 43, width: 720, height: 576, hTotal: 864, vTotal: 625, pixelClockKHz: 54000, interlaced: false),
        44: VICTiming(vic: 44, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 54000, interlaced: true),
        45: VICTiming(vic: 45, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 54000, interlaced: true),
        46: VICTiming(vic: 46, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 148500, interlaced: true),
        47: VICTiming(vic: 47, width: 1280, height: 720, hTotal: 1650, vTotal: 750, pixelClockKHz: 148500, interlaced: false),
        48: VICTiming(vic: 48, width: 720, height: 480, hTotal: 858, vTotal: 525, pixelClockKHz: 54000, interlaced: false),
        49: VICTiming(vic: 49, width: 720, height: 480, hTotal: 858, vTotal: 525, pixelClockKHz: 54000, interlaced: false),
        50: VICTiming(vic: 50, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 54000, interlaced: true),
        51: VICTiming(vic: 51, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 54000, interlaced: true),
        52: VICTiming(vic: 52, width: 720, height: 576, hTotal: 864, vTotal: 625, pixelClockKHz: 108000, interlaced: false),
        53: VICTiming(vic: 53, width: 720, height: 576, hTotal: 864, vTotal: 625, pixelClockKHz: 108000, interlaced: false),
        54: VICTiming(vic: 54, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 108000, interlaced: true),
        55: VICTiming(vic: 55, width: 1440, height: 576, hTotal: 1728, vTotal: 625, pixelClockKHz: 108000, interlaced: true),
        56: VICTiming(vic: 56, width: 720, height: 480, hTotal: 858, vTotal: 525, pixelClockKHz: 108000, interlaced: false),
        57: VICTiming(vic: 57, width: 720, height: 480, hTotal: 858, vTotal: 525, pixelClockKHz: 108000, interlaced: false),
        58: VICTiming(vic: 58, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 108000, interlaced: true),
        59: VICTiming(vic: 59, width: 1440, height: 480, hTotal: 1716, vTotal: 525, pixelClockKHz: 108000, interlaced: true),
        60: VICTiming(vic: 60, width: 1280, height: 720, hTotal: 3300, vTotal: 750, pixelClockKHz: 59400, interlaced: false),
        61: VICTiming(vic: 61, width: 1280, height: 720, hTotal: 3960, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        62: VICTiming(vic: 62, width: 1280, height: 720, hTotal: 3300, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        63: VICTiming(vic: 63, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 297000, interlaced: false),
        64: VICTiming(vic: 64, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 297000, interlaced: false),
        65: VICTiming(vic: 65, width: 1280, height: 720, hTotal: 3300, vTotal: 750, pixelClockKHz: 59400, interlaced: false),
        66: VICTiming(vic: 66, width: 1280, height: 720, hTotal: 3960, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        67: VICTiming(vic: 67, width: 1280, height: 720, hTotal: 3300, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        68: VICTiming(vic: 68, width: 1280, height: 720, hTotal: 1980, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        69: VICTiming(vic: 69, width: 1280, height: 720, hTotal: 1650, vTotal: 750, pixelClockKHz: 74250, interlaced: false),
        70: VICTiming(vic: 70, width: 1280, height: 720, hTotal: 1980, vTotal: 750, pixelClockKHz: 148500, interlaced: false),
        71: VICTiming(vic: 71, width: 1280, height: 720, hTotal: 1650, vTotal: 750, pixelClockKHz: 148500, interlaced: false),
        72: VICTiming(vic: 72, width: 1920, height: 1080, hTotal: 2750, vTotal: 1125, pixelClockKHz: 74250, interlaced: false),
        73: VICTiming(vic: 73, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 74250, interlaced: false),
        74: VICTiming(vic: 74, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 74250, interlaced: false),
        75: VICTiming(vic: 75, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 148500, interlaced: false),
        76: VICTiming(vic: 76, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 148500, interlaced: false),
        77: VICTiming(vic: 77, width: 1920, height: 1080, hTotal: 2640, vTotal: 1125, pixelClockKHz: 297000, interlaced: false),
        78: VICTiming(vic: 78, width: 1920, height: 1080, hTotal: 2200, vTotal: 1125, pixelClockKHz: 297000, interlaced: false),
        79: VICTiming(vic: 79, width: 1680, height: 720, hTotal: 3300, vTotal: 750, pixelClockKHz: 59400, interlaced: false),
        80: VICTiming(vic: 80, width: 1680, height: 720, hTotal: 3168, vTotal: 750, pixelClockKHz: 59400, interlaced: false),
        81: VICTiming(vic: 81, width: 1680, height: 720, hTotal: 2640, vTotal: 750, pixelClockKHz: 59400, interlaced: false),
        82: VICTiming(vic: 82, width: 1680, height: 720, hTotal: 2200, vTotal: 750, pixelClockKHz: 82500, interlaced: false),
        83: VICTiming(vic: 83, width: 1680, height: 720, hTotal: 2200, vTotal: 750, pixelClockKHz: 99000, interlaced: false),
        84: VICTiming(vic: 84, width: 1680, height: 720, hTotal: 2000, vTotal: 825, pixelClockKHz: 165000, interlaced: false),
        85: VICTiming(vic: 85, width: 1680, height: 720, hTotal: 2000, vTotal: 825, pixelClockKHz: 198000, interlaced: false),
        86: VICTiming(vic: 86, width: 2560, height: 1080, hTotal: 3750, vTotal: 1100, pixelClockKHz: 99000, interlaced: false),
        87: VICTiming(vic: 87, width: 2560, height: 1080, hTotal: 3200, vTotal: 1125, pixelClockKHz: 90000, interlaced: false),
        88: VICTiming(vic: 88, width: 2560, height: 1080, hTotal: 3520, vTotal: 1125, pixelClockKHz: 118800, interlaced: false),
        89: VICTiming(vic: 89, width: 2560, height: 1080, hTotal: 3300, vTotal: 1125, pixelClockKHz: 185625, interlaced: false),
        90: VICTiming(vic: 90, width: 2560, height: 1080, hTotal: 3000, vTotal: 1100, pixelClockKHz: 198000, interlaced: false),
        91: VICTiming(vic: 91, width: 2560, height: 1080, hTotal: 2970, vTotal: 1250, pixelClockKHz: 371250, interlaced: false),
        92: VICTiming(vic: 92, width: 2560, height: 1080, hTotal: 3300, vTotal: 1250, pixelClockKHz: 495000, interlaced: false),
        93: VICTiming(vic: 93, width: 3840, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        94: VICTiming(vic: 94, width: 3840, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        95: VICTiming(vic: 95, width: 3840, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        96: VICTiming(vic: 96, width: 3840, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        97: VICTiming(vic: 97, width: 3840, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        98: VICTiming(vic: 98, width: 4096, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        99: VICTiming(vic: 99, width: 4096, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        100: VICTiming(vic: 100, width: 4096, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        101: VICTiming(vic: 101, width: 4096, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        102: VICTiming(vic: 102, width: 4096, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        103: VICTiming(vic: 103, width: 3840, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        104: VICTiming(vic: 104, width: 3840, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        105: VICTiming(vic: 105, width: 3840, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 297000, interlaced: false),
        106: VICTiming(vic: 106, width: 3840, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        107: VICTiming(vic: 107, width: 3840, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        108: VICTiming(vic: 108, width: 1280, height: 720, hTotal: 2500, vTotal: 750, pixelClockKHz: 90000, interlaced: false),
        109: VICTiming(vic: 109, width: 1280, height: 720, hTotal: 2500, vTotal: 750, pixelClockKHz: 90000, interlaced: false),
        110: VICTiming(vic: 110, width: 1680, height: 720, hTotal: 2750, vTotal: 750, pixelClockKHz: 99000, interlaced: false),
        111: VICTiming(vic: 111, width: 1920, height: 1080, hTotal: 2750, vTotal: 1125, pixelClockKHz: 148500, interlaced: false),
        112: VICTiming(vic: 112, width: 1920, height: 1080, hTotal: 2750, vTotal: 1125, pixelClockKHz: 148500, interlaced: false),
        113: VICTiming(vic: 113, width: 2560, height: 1080, hTotal: 3750, vTotal: 1100, pixelClockKHz: 198000, interlaced: false),
        114: VICTiming(vic: 114, width: 3840, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        115: VICTiming(vic: 115, width: 4096, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        116: VICTiming(vic: 116, width: 3840, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 594000, interlaced: false),
        117: VICTiming(vic: 117, width: 3840, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 1188000, interlaced: false),
        118: VICTiming(vic: 118, width: 3840, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 1188000, interlaced: false),
        119: VICTiming(vic: 119, width: 3840, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 1188000, interlaced: false),
        120: VICTiming(vic: 120, width: 3840, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 1188000, interlaced: false),
        121: VICTiming(vic: 121, width: 5120, height: 2160, hTotal: 7500, vTotal: 2200, pixelClockKHz: 396000, interlaced: false),
        122: VICTiming(vic: 122, width: 5120, height: 2160, hTotal: 7200, vTotal: 2200, pixelClockKHz: 396000, interlaced: false),
        123: VICTiming(vic: 123, width: 5120, height: 2160, hTotal: 6000, vTotal: 2200, pixelClockKHz: 396000, interlaced: false),
        124: VICTiming(vic: 124, width: 5120, height: 2160, hTotal: 6250, vTotal: 2475, pixelClockKHz: 742500, interlaced: false),
        125: VICTiming(vic: 125, width: 5120, height: 2160, hTotal: 6600, vTotal: 2250, pixelClockKHz: 742500, interlaced: false),
        126: VICTiming(vic: 126, width: 5120, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 742500, interlaced: false),
        127: VICTiming(vic: 127, width: 5120, height: 2160, hTotal: 6600, vTotal: 2250, pixelClockKHz: 1485000, interlaced: false),
        193: VICTiming(vic: 193, width: 5120, height: 2160, hTotal: 5500, vTotal: 2250, pixelClockKHz: 1485000, interlaced: false),
        194: VICTiming(vic: 194, width: 7680, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 1188000, interlaced: false),
        195: VICTiming(vic: 195, width: 7680, height: 4320, hTotal: 10800, vTotal: 4400, pixelClockKHz: 1188000, interlaced: false),
        196: VICTiming(vic: 196, width: 7680, height: 4320, hTotal: 9000, vTotal: 4400, pixelClockKHz: 1188000, interlaced: false),
        197: VICTiming(vic: 197, width: 7680, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 2376000, interlaced: false),
        198: VICTiming(vic: 198, width: 7680, height: 4320, hTotal: 10800, vTotal: 4400, pixelClockKHz: 2376000, interlaced: false),
        199: VICTiming(vic: 199, width: 7680, height: 4320, hTotal: 9000, vTotal: 4400, pixelClockKHz: 2376000, interlaced: false),
        200: VICTiming(vic: 200, width: 7680, height: 4320, hTotal: 10560, vTotal: 4500, pixelClockKHz: 4752000, interlaced: false),
        201: VICTiming(vic: 201, width: 7680, height: 4320, hTotal: 8800, vTotal: 4500, pixelClockKHz: 4752000, interlaced: false),
        202: VICTiming(vic: 202, width: 7680, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 1188000, interlaced: false),
        203: VICTiming(vic: 203, width: 7680, height: 4320, hTotal: 10800, vTotal: 4400, pixelClockKHz: 1188000, interlaced: false),
        204: VICTiming(vic: 204, width: 7680, height: 4320, hTotal: 9000, vTotal: 4400, pixelClockKHz: 1188000, interlaced: false),
        205: VICTiming(vic: 205, width: 7680, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 2376000, interlaced: false),
        206: VICTiming(vic: 206, width: 7680, height: 4320, hTotal: 10800, vTotal: 4400, pixelClockKHz: 2376000, interlaced: false),
        207: VICTiming(vic: 207, width: 7680, height: 4320, hTotal: 9000, vTotal: 4400, pixelClockKHz: 2376000, interlaced: false),
        208: VICTiming(vic: 208, width: 7680, height: 4320, hTotal: 10560, vTotal: 4500, pixelClockKHz: 4752000, interlaced: false),
        209: VICTiming(vic: 209, width: 7680, height: 4320, hTotal: 8800, vTotal: 4500, pixelClockKHz: 4752000, interlaced: false),
        210: VICTiming(vic: 210, width: 10240, height: 4320, hTotal: 12500, vTotal: 4950, pixelClockKHz: 1485000, interlaced: false),
        211: VICTiming(vic: 211, width: 10240, height: 4320, hTotal: 13500, vTotal: 4400, pixelClockKHz: 1485000, interlaced: false),
        212: VICTiming(vic: 212, width: 10240, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 1485000, interlaced: false),
        213: VICTiming(vic: 213, width: 10240, height: 4320, hTotal: 12500, vTotal: 4950, pixelClockKHz: 2970000, interlaced: false),
        214: VICTiming(vic: 214, width: 10240, height: 4320, hTotal: 13500, vTotal: 4400, pixelClockKHz: 2970000, interlaced: false),
        215: VICTiming(vic: 215, width: 10240, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 2970000, interlaced: false),
        216: VICTiming(vic: 216, width: 10240, height: 4320, hTotal: 13200, vTotal: 4500, pixelClockKHz: 5940000, interlaced: false),
        217: VICTiming(vic: 217, width: 10240, height: 4320, hTotal: 11000, vTotal: 4500, pixelClockKHz: 5940000, interlaced: false),
        218: VICTiming(vic: 218, width: 4096, height: 2160, hTotal: 5280, vTotal: 2250, pixelClockKHz: 1188000, interlaced: false),
        219: VICTiming(vic: 219, width: 4096, height: 2160, hTotal: 4400, vTotal: 2250, pixelClockKHz: 1188000, interlaced: false),
    ]
}
