import Foundation

/// Bundled USB-IF vendor ID name lookup.
///
/// The TSV resource is generated by `scripts/update-vendor-db.sh` from
/// USB-IF's published vendor ID PDF. Re-run the script to refresh.
///
/// Parsed lazily on first use. The resulting dictionary is held for the
/// process lifetime; for ~13,000 entries that's ~few hundred KB resident
/// memory, which is fine for a menu-bar app.
///
/// Vendor ID 0 is intentionally not surfaced here even though USB-IF
/// assigns it to themselves: in PD identity contexts a zero VID means
/// "no vendor reported," which the trust signals layer treats as a
/// flagged condition. Returning a friendly name for it would contradict
/// that.
enum USBIFVendors {
    private static let table: [Int: String] = loadTable()

    /// Looks up a vendor name by VID. Returns nil if the VID isn't in
    /// the bundled list (or if the resource failed to load).
    static func name(for vendorID: Int) -> String? {
        guard vendorID != 0 else { return nil }
        return table[vendorID]
    }

    /// True if the VID is present in the bundled list. Distinct from
    /// `name(for:) != nil` only for VID 0, which is filtered out of
    /// the public lookup but still present in the underlying table.
    static func isRegistered(_ vendorID: Int) -> Bool {
        table[vendorID] != nil
    }

    /// Number of entries in the bundled list. Exposed for diagnostics
    /// and tests; the absolute number depends on the bundled PDF
    /// vintage.
    static var entryCount: Int { table.count }

    private static func loadTable() -> [Int: String] {
        guard let url = Bundle.module.url(
            forResource: "usbif-vendors",
            withExtension: "tsv"
        ) else {
            return [:]
        }
        guard let text = try? String(contentsOf: url, encoding: .utf8) else {
            return [:]
        }

        var map: [Int: String] = [:]
        map.reserveCapacity(15000)
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            // Skip header / metadata comments.
            if line.first == "#" { continue }
            guard let tab = line.firstIndex(of: "\t") else { continue }
            let vidPart = line[..<tab]
            let namePart = line[line.index(after: tab)...]
            guard let vid = Int(vidPart), !namePart.isEmpty else { continue }
            map[vid] = String(namePart)
        }
        return map
    }
}
