import Foundation

/// Bundled USB-IF vendor ID name lookup.
///
/// The TSV resource is generated by `scripts/update-vendor-db.sh` from
/// USB-IF's published vendor ID PDF. Re-run the script to refresh.
///
/// Parsed lazily on first use. The resulting dictionary is held for the
/// process lifetime; for ~13,000 entries that's ~few hundred KB resident
/// memory, which is fine for a menu-bar app.
///
/// Vendor ID 0 is intentionally not surfaced here even though USB-IF
/// assigns it to themselves: in PD identity contexts a zero VID means
/// "no vendor reported," which the trust signals layer treats as a
/// flagged condition. Returning a friendly name for it would contradict
/// that.
enum USBIFVendors {
    private static let table: [Int: String] = loadTable()

    /// Looks up a vendor name by VID. Returns nil if the VID isn't in
    /// the bundled list (or if the resource failed to load).
    static func name(for vendorID: Int) -> String? {
        guard vendorID != 0 else { return nil }
        return table[vendorID]
    }

    /// True if the VID is present in the bundled list. Distinct from
    /// `name(for:) != nil` only for VID 0, which is filtered out of
    /// the public lookup but still present in the underlying table.
    static func isRegistered(_ vendorID: Int) -> Bool {
        table[vendorID] != nil
    }

    /// Number of entries in the bundled list. Exposed for diagnostics
    /// and tests; the absolute number depends on the bundled PDF
    /// vintage.
    static var entryCount: Int { table.count }

    private static func loadTable() -> [Int: String] {
        guard let url = findResourceURL(),
              let text = try? String(contentsOf: url, encoding: .utf8) else {
            return [:]
        }

        var map: [Int: String] = [:]
        map.reserveCapacity(15000)
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            // Skip header / metadata comments.
            if line.first == "#" { continue }
            guard let tab = line.firstIndex(of: "\t") else { continue }
            let vidPart = line[..<tab]
            let namePart = line[line.index(after: tab)...]
            guard let vid = Int(vidPart), !namePart.isEmpty else { continue }
            map[vid] = String(namePart)
        }
        return map
    }

    /// Resolve the bundled TSV's URL across the contexts WhatCableCore
    /// runs in: SwiftPM tests / `swift run`, the .app's GUI binary in
    /// Contents/MacOS/, and the CLI binary in Contents/Helpers/. We
    /// avoid `Bundle.module` because its generated accessor calls
    /// `fatalError` when the bundle isn't found, which would crash
    /// the CLI inside the .app (none of its candidate paths resolve
    /// to Contents/Resources/ for a helper executable). On failure we
    /// return nil so the caller can fall back to an empty lookup,
    /// degrading gracefully to "Unregistered / unknown" instead of
    /// crashing.
    private static func findResourceURL() -> URL? {
        let bundleName = "WhatCable_WhatCableCore"
        let resourceFile = "usbif-vendors"
        let resourceExt = "tsv"
        let fm = FileManager.default

        var roots: [URL] = []

        // SwiftPM tests set PACKAGE_RESOURCE_BUNDLE_PATH (or the older
        // PACKAGE_RESOURCE_BUNDLE_URL) so the test runner can find the
        // resource bundle next to the build output. Honor it first
        // since SwiftPM's own Bundle.module does.
        let env = ProcessInfo.processInfo.environment
        if let override = env["PACKAGE_RESOURCE_BUNDLE_PATH"] ?? env["PACKAGE_RESOURCE_BUNDLE_URL"] {
            roots.append(URL(fileURLWithPath: override))
        }

        // Standard SwiftPM Bundle.module candidates: the main bundle's
        // resources (.app/Contents/Resources for the GUI) and the
        // directory containing the running binary (covers `swift run`
        // and statically-linked frameworks).
        if let r = Bundle.main.resourceURL { roots.append(r) }
        if let r = Bundle(for: BundleFinder.self).resourceURL { roots.append(r) }
        roots.append(Bundle.main.bundleURL)
        roots.append(Bundle.main.bundleURL.deletingLastPathComponent())

        // For SwiftPM tests, the resource bundle is a sibling of the
        // .xctest bundle, not inside it. Bundle(for: BundleFinder.self)
        // resolves to the .xctest in tests; its parent directory is
        // where SPM places the resource bundle.
        roots.append(Bundle(for: BundleFinder.self).bundleURL.deletingLastPathComponent())

        // For a CLI helper at .app/Contents/Helpers/whatcable, walk up
        // to the .app and look in Contents/Resources/. Bundle.main for
        // a non-bundled executable points at the executable itself,
        // and SwiftPM's Bundle.module lookup chain doesn't cover this.
        if let exe = Bundle.main.executableURL {
            let parent = exe.deletingLastPathComponent()           // Contents/Helpers
            let contents = parent.deletingLastPathComponent()      // Contents
            roots.append(contents.appendingPathComponent("Resources"))
        }

        for root in roots {
            // SwiftPM resource bundle layout.
            let viaBundle = root
                .appendingPathComponent("\(bundleName).bundle")
                .appendingPathComponent("\(resourceFile).\(resourceExt)")
            if fm.fileExists(atPath: viaBundle.path) {
                return viaBundle
            }
            // Loose-file layout (not currently used, but cheap to check
            // and means the loader keeps working if we ever simplify
            // the bundling).
            let loose = root.appendingPathComponent("\(resourceFile).\(resourceExt)")
            if fm.fileExists(atPath: loose.path) {
                return loose
            }
        }
        return nil
    }
}

private final class BundleFinder {}
